# 坐标系下的线性变换

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625111314.png"/>

要求解这个对称转化对应的矩阵T有点复杂，但是如果L是x轴，就会变得很简单

其实在其他坐标系，L就有可能是x轴

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625121408.png"/>

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625112459.png"/>

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625121501.png"/>

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625113200.png"/>

用代码实现:

In [4]:
# 直角坐标系转化成 y=1/2x  为x轴的坐标系
import numpy as np

# 新坐标系下的两个基向量
b_1 = np.array([[2], [1]])
b_2 = np.array([[-1], [2]])
b = np.array([[2, -1], [1, 2]])

# b 的逆
b_ni = np.linalg.inv(b)

# 关于x 轴求对称的矩阵转化
t = np.array([
    [1, 0],
    [0, -1]
])
# 完整的原坐标系的transform
new_t = b.dot(t).dot(b_ni)
print('笛卡尔空间的T为:\n', new_t)


# 求对称
def duichen(x):
    return new_t.dot(x)


print('[1,0.5] 关于y=1/2x对称以后是\n', duichen(np.array([[1], [0.5]])))

笛卡尔空间的T为:
 [[ 0.6  0.8]
 [ 0.8 -0.6]]
[1,0.5] 关于y=1/2x对称以后是
 [[1. ]
 [0.5]]


另一个例子

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625115428.png"/>

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625121758.png"/>

In [7]:
B = np.array([
    [1,1,0],
    [1,0,1],
    [0,1,1]
])
B_ni = np.linalg.inv(B)
C = np.array([
    [1,3,2],
    [2,-1,0],
    [1,1,1]
])
T_B = B_ni.dot(C)
T = B.dot(T_B).dot(B_ni)
T 

array([[ 1. ,  0. ,  2. ],
       [ 0.5,  1.5, -1.5],
       [ 0.5,  0.5,  0.5]])

In [8]:
# 验证
T.dot(B)

array([[ 1.,  3.,  2.],
       [ 2., -1.,  0.],
       [ 1.,  1.,  1.]])

In [9]:
C

array([[ 1,  3,  2],
       [ 2, -1,  0],
       [ 1,  1,  1]])

In [10]:
T.dot(B) == C

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])