# 正交投影

### 正交补集

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625162329.png"/>

比如S是二维空间中W线上的向量，正交补集就是跟他垂直的线上的向量，如果S是二维空间中所有的向量，正交补集就是{0}

正交补集的性质

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625164956.png"/>

这个就太直观了：
<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625165230.png"/>

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625165413.png"/>

这个也很直观

随便你怎么线性组合正交补集的向量，他依然与对应的所有S里的向量正交

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625165851.png"/>

因为W = （Span B）

根据第二条性质也很直观

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625170227.png"/>

假设u同时属于S和S的正交补集,那么u跟自己做内积肯定是0

所以u也是0

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625171552.png"/>

A的行空间的正交补集等于A的零空间

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625173528.png"/>

同样易知 只要把A替换成A的转置就可以

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625173805.png"/>
比如说一个三维空间，某一个子空间是一个平面，它的维度是2，跟他正交的肯定是一条直线，维度是1 加起来是3

如果子空间就是这个三维空间，正交补集就是0 ，维度和也是3

证明：
<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625183722.png"/>

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625184356.png"/>
<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625185210.png"/>

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625185948.png"/>
<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625191429.png"/>

### 什么是正交投影

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625191734.png"/>
找出w的部分这个过程也是线性的变换
<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210625192514.png"/>

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210626045929.png"/>


<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210626051440.png"/>

### 如何计算正交投影

求正交投影的过程也是一个线性变换

已知一个向量u 求他在子空间W上的正交投影w：

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210626051847.png"/>

拿这个公式来验证一下：

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210627122843.png"/>

In [1]:
import numpy as np


def orthogonal_projection(v, c):
    cTc = c.T.dot(c)
    cTc_ni = np.linalg.inv(cTc)
    w = c.dot(cTc_ni).dot(c.T).dot(v)
    return w


v = np.array([
    [1],
    [4]
])

c = np.array([
    [1],
    [1]
])
c_1 = np.array([
    [1],
    [-1]
])
y_x = orthogonal_projection(v, c)
y__x = orthogonal_projection(v, c_1)
print('在y=x上的投影:\n', y_x)
print('在y=-x上的投影:\n', y__x)
print('投影之和:\n', y_x + y__x)


在y=x上的投影:
 [[2.5]
 [2.5]]
在y=-x上的投影:
 [[-1.5]
 [ 1.5]]
投影之和:
 [[1.]
 [4.]]


这个公式成立的前提是C乘以C的转置是可逆的，接下来进行证明:

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210627122944.png"/>

如何记忆这个公式

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210627110458.png"/>

其实这个公式就是丁丁

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210627110615.png"/>

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210627110814.png"/>

有一天他右边的耳朵掉了，然后用锤子和钉子给他订上，但是钉反了



<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210627111046.png"/>

### 正交投影的应用

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210627123101.png"/>

线性回归任务：

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210627114438.png"/>
<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210627123532.png"/>
<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210627114934.png"/>
<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210627123559.png"/>
<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210627115145.png"/>

令

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210627115206.png"/>

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210627123139.png"/>

接下来拟合下面一组数据

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210627120325.png"/>

In [5]:
import numpy as np

x = [2.6, 2.72, 2.75, 2.67, 2.68]
y = [2, 2.1, 2.1, 2.03, 2.04]
count = len(x)

C = np.zeros((count,2))

for j in range(count):
    C[j][1] = x[j]
    C[j][0] = 1

y = np.array(y).T

def orthogonal_projection(y, c):
    cTc = c.T.dot(c)
    cTc_ni = np.linalg.inv(cTc)
    a = cTc_ni.dot(c.T).dot(y)
    return a

print('最优解a\n',orthogonal_projection(y,C))

最优解a
 [0.0555418  0.74458204]


也可以拟高次的方程，比如拟合抛物线

<img src="https://raw.githubusercontent.com/xuyouqian/picgo/master/20210627122130.png"/>